export enum WsMessageName {
  Allocate = "ALLOCATE",
  CancelEngagement = "CANCEL_ENGAGEMENT",
  ConfirmPosition = "CONFIRM_POSITION",
  GetMissionsList = "GET_MISSIONS_LIST",
  DeleteMission = "DELETE_MISSION",
  LoadMission = "LOAD_MISSION",
  LosRequest = "LOS_REQUEST",
  Ping = "PING",
  /** שליחת מסמך XML מהלקוח לשרת (גוף ב־data.xml) */
  SendXml = "SEND_XML",
  SaveMission = "SAVE_MISSION",
  SaveEntity = "SAVE_ENTITY",
  UpdateEntity = "UPDATE_ENTITY",
  EntityCreated = "ENTITY_CREATED",
  SetPosition = "SET_POSITION",
  SetRadarParams = "SET_RADAR_PARAMS",
  SetTabooZone = "SET_TABOO_ZONE",
  SetTargetInfo = "SET_TARGET_INFO",
  SystemMode = "SYSTEM_MODE",
  EntityDeleted = "ENTITY_DELETED",
  EntityPosition = "ENTITY_POSITION",
  EntityUpdated = "ENTITY_UPDATED",
  LosSector = "LOS_SECTOR",
  LoadResult = "LOAD_RESULT",
  /** שרת → לקוח: מאגר ישויות ומשימות מלא אחרי התחברות / עדכון */
  GetDb = "GET_DB",
  Error = "ERROR",
  MissionsList = "MISSIONS_LIST",
  MissionsListUpdate = "MISSIONS_LIST_UPDATE",
  MissionData = "MISSION_DATA",
  MissionDataUpdate = "MISSION_DATA_UPDATE",
  Position = "POSITION",
  /** מחליף את POSITION — פרמטרי מיקום / TMAPS מהשרת */
  TmapsParams = "TMAPS_PARAMS",
  RadarUpdate = "RADAR_UPDATE",
  SaveResult = "SAVE_RESULT",
  RecommendAssignment = "RECOMMEND_ASSIGNMENT",
  TargetUpdate = "TARGET_UPDATE",
  LosResult = "LOS_RESULT",
  LosUpdate = "LOS_UPDATE",
  TargetsData = "TARGETS_DATA",
  RadarStatus = "RADAR_STATUS",
  RadarParamsUpdate = "RADAR_PARAMS_UPDATE",
  RadarBitStatusUpdate = "RADAR_BIT_STATUS_UPDATE",
  ConfirmUpdate = "CONFIRM_UPDATE",
  SystemStatusM = "SYSTEM_STATUS_M",
  RadarParams = "RADAR_PARAMS",
  RadarBitStatus = "RADAR_BIT_STATUS",
  TargetAssigned = "TARGET_Assigned",
  TargetLock = "TARGET_LOCK",
  SystemStatus = "SYSTEM_STATUS",
  TargetDestroyed = "TARGET_DESTROYED",
  GunBitStatus = "GUN_BIT_STATUS",
  MissilePosition = "MISSILE_POSITION",
}
